name: flutter_youtube_ui
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  badges: ^2.0.2
  flutter:
    sdk: flutter

  # flutter_icons: ^1.1.0
  flutter_riverpod: ^0.13.1+1
  http: ^0.13.4
  miniplayer: ^1.0.0+2
  timeago: ^3.0.2
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/yt_logo_dark.png
